### ISSUE TITLE
Error: The esbuild JavaScript API cannot be bundled.

### ISSUE THREAD

**Issue by loekup** [ArtiomTr/jest-coverage-report-action#314]
### Describe a bug

While trying to run the report action in our github workflow we run into the following problem:

```Begin stages.parsethreshold...
Warning:  Failed to parse jest configuration. "coverageThreshold" from config file will be ignored. Error: The esbuild JavaScript API cannot be bundled. Please mark the "esbuild" package as external so it's not included in the bundle.

More information: The file containing the code for esbuild's JavaScript API (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.5/dist/index.js) does not appear to be inside the esbuild package on the file system, which usually means that the esbuild package was bundled into another file. This is problematic because the API needs to run a binary executable inside the esbuild package which is located using a relative path from the API code to the executable. If the esbuild package is bundled, the relative path will be incorrect and the executable won't be found.
    at jg (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.5/dist/index.js:20:1749)
    at na (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.5/dist/index.js:22:2524)
    at fG (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.5/dist/index.js:22:1155)
    at transpileAndParseConfiguration (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.5/dist/index.js:23:5966)
    at Object.parseTsConfiguration [as .ts] (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.5/dist/index.js:23:6526)
    at parseConfiguration (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.5/dist/index.js:23:6691)
    at parseConfigurations (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.5/dist/index.js:23:7151)
    at async bw (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.5/dist/index.js:52:[36](https://github.com/albumprinter/Editor-Platform/actions/runs/3045181383/jobs/4906424473#step:7:38)4)
    at async Sw (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.5/dist/index.js:52:581)
    at async je (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2.0.5/dist/index.js:51:156)
stages.parseThreshold ended
```

Which in turn results in the action actually reporting the right amount of coverage, but doesn't consider the threshold set in the `jest.config.js`

### Expected behavior

We expect the following green dots, to be red as the expected threshold is not a 100% as described in our jest.config.js (see details below)

![image](https://user-images.githubusercontent.com/3018636/189908900-5559064c-c339-4398-8c39-6f6ed89c2b55.png)

### Details

-   Action version: v2.0.9
-  Jest version: 29.0.3
-   <details><summary>action.yml file</summary>
```yml
jobs:
  unit_tests:
    name: 'Unit tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - name: Run yarn install
        run: yarn install --immutable
      - name: Run tests
        run: yarn test:ci
      - name: Create reports
        if: success() || failure()
        uses: ArtiomTr/jest-coverage-report-action@v2.0.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
          skip-step: all
          coverage-file: report.json
          base-coverage-file: report.json
```
</details>

-   <details><summary>jest.config.js file</summary>
```javascript
const { defaults: tsjPreset } = require("ts-jest/presets");

module.exports = {
  testEnvironment: "node",
  preset: "ts-jest",
  snapshotFormat: {
    escapeString: true,
    printBasicPrototype: true,
  },
  transform: {
    ...tsjPreset.transform,
    "<regex_match_files>": [
      "ts-jest",
      {
        diagnostics: false,
        isolatedModules: true,
        tsconfig: {
          target: "ES2020", // to support nodejs@14
          noEmitHelpers: false,
        },
      },
    ],
  },
  verbose: true,
  coverageDirectory: "coverage",
  coverageReporters: ["text", "text-summary", "lcov"],
  // https://jestjs.io/docs/configuration#coveragethreshold-object
  coverageThreshold: {
    global: {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
  },
  projects: ["<rootDir>/packages/*", "<rootDir>/products/*"],
};
```
</details>

### Additional context

the `yarn test:ci` command contains the following: `yarn jest --silent --ci --coverage --testLocationInResults --json --outputFile="report.json"`

**Comment by ArtiomTr** [comment]
Hello @loekup :wave:,

Sorry for the late response. I will try to fix that

**Comment by joehoppe** [comment]
Do you know what version that started in. Trying to rollback to a previous one. Thanks!

**Comment by loekup** [comment]
Hey @ArtiomTr any update on this ?

**Comment by ArtiomTr** [comment]
Hello @loekup :wave:,

The bug should be fixed now. The fix is available under tag `v2.1.2` or just `v2`

**Comment by jmotes** [comment]
@loekup I'm still having this issue on a Next.js project. I reverted to v2.1.3 but the issue exists there as well.

```
Begin stages.parsethreshold...
Warning:  Failed to parse jest configuration. "coverageThreshold" from config file will be ignored. Error: > Couldn't find a `pages` directory. Please create one under the project root
    at Object.findPagesDir (/home/runner/work/thrive/thrive/frontend/node_modules/next/dist/lib/find-pages-dir.js:42:19)
```
I wonder if I might be doing something wrong but thought I'd post here incase you've seen this with Next.js before. 

Thanks!
